version: "3.1"
services:
  jenkins:
    image: superjenkins
    networks:
      jenkins:
    volumes:
      - /opt/jenkins/data/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/jenkins/ssh/:/root/.ssh/
    ports:
      - 80:8080


##init the swarm
#`docker swarm init`

##Deploy the stack
#`docker stack deploy -c jenkins-nginx.yml jenkins`
